[package]
name = "zingo-rpc"
version = "0.1.0"
authors = ["zingo@zingolabs.org"]
edition = "2021"

[features]
test = []
# NOTE: Deprecated
nym_poc = []

[dependencies]
zcash_client_backend = { workspace = true, features = ["lightwalletd-tonic"] }
zingo-netutils = { workspace = true }

nym-sdk = { workspace = true }
nym-sphinx-addressing = { workspace = true }
nym-validator-client = { workspace = true }
nym-bin-common = { workspace = true }
nym-sphinx-anonymous-replies = { workspace = true }

http = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tonic = { workspace = true }
prost = { workspace = true }
bytes = { workspace = true }
http-body = { workspace = true }

tokio-rustls = "0.23.3"
tower = { version = "0.4" }
hyper-rustls = { version = "0.23", features = ["http2"] }
webpki-roots = "0.21.0"
hyper = { version = "0.14", features = ["full"] }
rustls-pemfile = "1.0.0"

futures = "0.3"
futures-core = "0.3"

# [build-dependencies]
# tonic-build = "0.10.2"
